name: Trigger auto deployment for zep

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/zep-AutoDeployTrigger-28f49361-550d-43f2-bfd2-ab4d9a0c7af3.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ZEP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: lolabyleaf.azurecr.io
          registryUsername: ${{ secrets.ZEP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZEP_REGISTRY_PASSWORD }}
          containerAppName: zep
          resourceGroup: lolabyleaf
          imageToBuild: lolabyleaf.azurecr.io/zep:${{ github.sha }}
          dockerfilePath: Dockerfile

     

